services:
  - type: web
    name: text-to-speech
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: AWS_ACCESS_KEY
        sync: false
      - key: AWS_SECRET_KEY
        sync: false
      - key: AWS_REGION
        sync: false
      - key: S3_BUCKET
        sync: false
      - key: PORT
        value: 5000